// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: 
/// ```dart
/// import 'firebase_options.dart'; 
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunROgciTCsfiXWYfvTyVXRSVSmPlJSh8',
    appId: '1:1048412238130:web:16fd935e1fc1411627272b',
    messagingSenderId: '1048412238130',
    projectId: 'profit-app-ee191',
    authDomain: 'profit-app-ee191.firebaseapp.com',
    storageBucket: 'profit-app-ee191.firebasestorage.app',
    measurementId: 'G-EECGJGNWKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0DBhZPAWhZeMcaRZZAgAR-2_rJCnvug',
    appId: '1:1048412238130:android:7f36afbfc6ce38cd27272b',
    messagingSenderId: '1048412238130',
    projectId: 'profit-app-ee191',
    storageBucket: 'profit-app-ee191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2SmqG7Wwd0hrEnRxCaI6B8JY8omJTZAM',
    appId: '1:1048412238130:ios:72842fec8471f2f427272b',
    messagingSenderId: '1048412238130',
    projectId: 'profit-app-ee191',
    storageBucket: 'profit-app-ee191.firebasestorage.app',
    iosBundleId: 'com.example.profitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2SmqG7Wwd0hrEnRxCaI6B8JY8omJTZAM',
    appId: '1:1048412238130:ios:72842fec8471f2f427272b',
    messagingSenderId: '1048412238130',
    projectId: 'profit-app-ee191',
    storageBucket: 'profit-app-ee191.firebasestorage.app',
    iosBundleId: 'com.example.profitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAunROgciTCsfiXWYfvTyVXRSVSmPlJSh8',
    appId: '1:1048412238130:web:f78abbe8e9b81f2e27272b',
    messagingSenderId: '1048412238130',
    projectId: 'profit-app-ee191',
    authDomain: 'profit-app-ee191.firebaseapp.com',
    storageBucket: 'profit-app-ee191.firebasestorage.app',
    measurementId: 'G-FQ8KQTHZLP',
  );
}
